//! The documentation site.
//!
//! `cli/src/docs/**` and the repository README, rendered to static HTML with
//! no dependency, no build step, and no highlighter in the browser. One
//! command builds it and one flag checks it:
//!
//! ```text
//! cargo run -p website                 # into target/docs-site
//! cargo run -p website -- serve        # and read it on localhost
//! cargo run -p website -- --check      # every link it wrote, followed
//! ```
//!
//! Nothing here writes into the checked-out tree. The output goes under
//! `target/`, which the repository already ignores, and the documentation is
//! read and never modified — the pages are the maintainer's, and a generator
//! that edited them would be a second author.
#![allow(
    clippy::print_stdout,
    clippy::print_stderr,
    reason = "what was written, and why it could not be, is this command's \
              own output; there is no diagnostic session to route it through"
)]

pub mod check;
pub mod highlight;
pub mod links;
pub mod markdown;
pub mod options;
pub mod pages;
pub mod render;
pub mod serve;
pub mod themes;

use crate::options::{Command, Options};
use crate::pages::Site;
use crate::render::PageLinks;
use std::path::{Path, PathBuf};

/// Written at the top of every generated site, and the only thing that lets
/// the generator clear an output directory: without it, a directory somebody
/// pointed `--out` at by mistake is left exactly as it was.
const MARKER: &str = ".website-generated";

const MARKER_TEXT: &str = "Generated by `cargo run -p website`. Everything beside this file is \
                           overwritten on the next build.\n";

/// Renders the whole site into `out`, and reports what each page pointed at.
pub fn build(site: &Site, out: &Path) -> Result<Vec<PageLinks>, String> {
    prepare(out)?;
    write(&out.join("assets/site.css"), themes::stylesheet().as_bytes())?;
    let mut built = Vec::with_capacity(site.pages.len());
    for page in &site.pages {
        let (html, links) = render::document(site, page);
        write(&out.join(&page.route).join("index.html"), html.as_bytes())?;
        built.push(links);
    }
    write(&out.join(MARKER), MARKER_TEXT.as_bytes())?;
    Ok(built)
}

/// Empties an output directory this generator wrote before, creates one that
/// does not exist, and refuses anything else.
fn prepare(out: &Path) -> Result<(), String> {
    match std::fs::read_dir(out) {
        Err(_) => {}
        Ok(mut entries) => {
            if entries.next().is_some() && !out.join(MARKER).is_file() {
                return Err(format!(
                    "{} is not empty and was not generated here, so it is left alone",
                    out.display()
                ));
            }
            std::fs::remove_dir_all(out).map_err(|why| format!("{}: {why}", out.display()))?;
        }
    }
    std::fs::create_dir_all(out).map_err(|why| format!("{}: {why}", out.display()))
}

fn write(path: &Path, bytes: &[u8]) -> Result<(), String> {
    if let Some(directory) = path.parent() {
        std::fs::create_dir_all(directory).map_err(|why| format!("{}: {why}", directory.display()))?;
    }
    std::fs::write(path, bytes).map_err(|why| format!("{}: {why}", path.display()))
}

/// The checkout to read, from `--root` or from wherever the command was run.
fn root_of(options: &Options) -> Result<PathBuf, String> {
    if let Some(root) = &options.root {
        return pages::find_root(root).ok_or_else(|| {
            format!("{} does not hold `cli/src/docs` and a README", root.display())
        });
    }
    let here = std::env::current_dir().map_err(|why| format!("the working directory: {why}"))?;
    pages::find_root(&here).ok_or_else(|| {
        format!(
            "no Buri checkout above {}; run this from the repository, or pass `--root`",
            here.display()
        )
    })
}

/// The whole command. Returns the process's exit code.
pub fn run(arguments: &[String]) -> i32 {
    let options = match options::parse(arguments) {
        Ok(options) => options,
        Err(why) => return fail(&why),
    };
    if options.command == Command::Help {
        println!("{}", options::USAGE);
        return 0;
    }
    let root = match root_of(&options) {
        Ok(root) => root,
        Err(why) => return fail(&why),
    };
    let site = match pages::read(&root) {
        Ok(site) => site,
        Err(why) => return fail(&why),
    };
    match options.command {
        Command::Help => 0,
        Command::Check => check(&site),
        Command::Build | Command::Serve => {
            let out = options
                .out
                .clone()
                .unwrap_or_else(|| root.join(options::DEFAULT_OUTPUT));
            let built = match build(&site, &out) {
                Ok(built) => built,
                Err(why) => return fail(&why),
            };
            println!("{} pages written to {}", built.len(), out.display());
            if options.command == Command::Serve {
                return serve::serve(&root, &out, options.port, options.watch);
            }
            0
        }
    }
}

/// Builds into a temporary directory and follows every link it wrote.
fn check(site: &Site) -> i32 {
    let out = std::env::temp_dir().join(format!("buri-website-check-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&out);
    let built = match build(site, &out) {
        Ok(built) => built,
        Err(why) => return fail(&why),
    };
    let problems = check::problems(site, &built, &out);
    let _ = std::fs::remove_dir_all(&out);
    if problems.is_empty() {
        println!("{} pages, every link resolves", built.len());
        return 0;
    }
    let mut report = format!("{} broken links:\n", problems.len());
    for problem in &problems {
        report.push_str(&format!("  {problem}\n"));
    }
    fail(report.trim_end())
}

fn fail(why: &str) -> i32 {
    eprintln!("website: {why}");
    1
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The bar in the root `Cargo.toml`, applied to this crate. `buri` is not
    /// a dependency under it — it is this repository's own crate, reached by
    /// path — and the site must not acquire one that is.
    ///
    /// `cli/tests/language/corpus.rs` holds `cli/Cargo.toml` to the same
    /// claim. This is the second workspace member, so it needs its own.
    #[test]
    fn nothing_is_resolved_from_crates_io() {
        let manifest = std::fs::read_to_string(
            Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.toml"),
        )
        .expect("the crate's own manifest");
        let mut in_dependencies = false;
        let mut seen = 0;
        for line in manifest.lines() {
            let line = line.trim();
            if line.starts_with('[') {
                in_dependencies = line.contains("dependencies");
                continue;
            }
            if !in_dependencies || line.is_empty() || line.starts_with('#') {
                continue;
            }
            assert_eq!(
                line, "buri = { path = \"../cli\" }",
                "the site declares `{line}`. The only thing it may depend on is the \
                 toolchain in this repository, by path: everything else is a dependency, \
                 and the bar in the root Cargo.toml is what it would have to clear."
            );
            seen += 1;
        }
        assert_eq!(seen, 1, "the path dependency on `buri` vanished; this test asserts nothing");
    }

    /// The output directory is under `target/`, which `.gitignore` already
    /// covers. A generated site that could be committed eventually is.
    #[test]
    fn the_default_output_is_ignored_by_git() {
        let gitignore = std::fs::read_to_string(
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../.gitignore"),
        )
        .expect("the repository's .gitignore");
        assert!(options::DEFAULT_OUTPUT.starts_with("target/"));
        assert!(
            gitignore.lines().any(|line| line.trim() == "target/"),
            "`target/` is no longer ignored, so `{}` would be committable",
            options::DEFAULT_OUTPUT
        );
    }

    #[test]
    fn a_directory_the_generator_did_not_write_is_left_alone() {
        let out = std::env::temp_dir().join(format!("buri-website-guard-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&out);
        std::fs::create_dir_all(&out).expect("a temporary directory");
        std::fs::write(out.join("something-of-yours.txt"), b"kept").expect("a file in it");
        assert!(prepare(&out).is_err());
        assert!(out.join("something-of-yours.txt").is_file(), "it was not left alone");
        let _ = std::fs::remove_dir_all(&out);
    }
}
