[package]
name = "buri-js"
version = "0.3.19"
edition = "2021"
description = "The Buri JavaScript backend."
license = "MIT"
repository = "https://github.com/buri-lang/buri"
rust-version = "1.89"

[dependencies]
buri-backend = { path = "../backend", version = "0.3.19" }
buri-diagnostics = { path = "../diagnostics", version = "0.3.19" }
buri-hash = { path = "../hash", version = "0.3.19" }
buri-middle = { path = "../middle", version = "0.3.19" }
buri-semantics = { path = "../semantics", version = "0.3.19" }

[lints]
workspace = true
