//! `core/char` — the eight entries a `Char` cannot answer for itself.
//!
//! `char.buri` declares nine methods and this file is eight of them; `toU32` is
//! the ninth and is a representation change the backend open-codes, because a
//! `Char` **is** a `U32` (`char.buri`: "Exact: every `Char` is a `U32`").
//!
//! `lib.rs` §0 divided the intrinsic surface into what a generated program
//! cannot do for itself and what has no single right answer, and put
//! `core/char`'s classifiers in the **second** group — beside `core/math`'s
//! transcendentals — with `isAlpha` as the reason: "implementing `isAlpha` with
//! Rust's `is_alphabetic` against JavaScript's `\p{L}` would put a divergence
//! into the toolchain that shows up on one input in a few thousand". That
//! sentence is still true and this file does not do it. What it does instead is
//! §1.
//!
//! ## 1. `isAlpha` is `\p{L}`, and `\p{L}` is a table
//!
//! `runtime.js`'s `$char_isAlpha` is `/^\p{L}$/u.test(c)`, which is General
//! Category `L` — `Lu | Ll | Lt | Lm | Lo`. Rust's `char::is_alphabetic` is the
//! **Alphabetic** derived property, which is `L` plus `Nl` (the letter numbers:
//! Roman numerals, Cuneiform numerals) plus `Other_Alphabetic` (about thirteen
//! hundred combining marks used by the Indic, Hebrew and Arabic scripts). They
//! differ on roughly fifteen hundred characters, and none of them is one a test
//! for "is this a letter" would think to try — which is exactly the failure
//! `lib.rs` §0 refused to ship.
//!
//! There is no General Category in `std`, and there is no third place to get
//! one: `cli/build.rs` compiles this crate with a bare `rustc` invocation and
//! no Cargo, so it has `std` and nothing else, by construction rather than by
//! policy.
//!
//! So the category is **data in this file**, and the data's source is the one
//! source that cannot be wrong about it: [`LETTER`] was generated by asking the
//! JavaScript engine the JavaScript backend runs on. The generator is six lines
//! and is in this comment rather than in a script, because a script nobody runs
//! is a script nobody trusts:
//!
//! ```js
//! const L = /^\p{L}$/u, out = [];
//! let start = -1;
//! for (let cp = 0; cp <= 0x10ffff; cp++) {
//!   if (cp >= 0xd800 && cp <= 0xdfff) { if (start >= 0) { out.push([start, cp - 1]); start = -1; } continue; }
//!   const ok = L.test(String.fromCodePoint(cp));
//!   if (ok && start < 0) start = cp;
//!   if (!ok && start >= 0) { out.push([start, cp - 1]); start = -1; }
//! }
//! ```
//!
//! **Unicode 16.0**, which is what `bun` 1.2.13 answers — checked by the two
//! scripts that version added, Todhri (U+105C0) and Kirat Rai (U+16D40), both of
//! which the table contains. That is a version and not a guess, and it is the
//! one number a reader has to know to regenerate it: a newer engine adds
//! letters, and the difference is exactly the characters that Unicode version
//! added.
//!
//! Two things this deliberately does *not* do:
//!
//!   * It does not derive the table from `char::is_alphabetic` by subtracting an
//!     exception set. That would pin the answer to *two* Unicode versions —
//!     `rustc`'s and the exception table's — and make a rustc upgrade able to
//!     change `isAlpha` without anything in this repository changing.
//!   * It does not table the **case** mappings. `str.toUpper` has used Rust's
//!     `str::to_uppercase` against JavaScript's `String#toUpperCase` since it
//!     was first written (`text.rs`), because those are the same Unicode
//!     operation implemented from the same specification, and `isUpper`,
//!     `isLower`, `toUpper` and `toLower` here are that same trust applied one
//!     scalar at a time. `isAlpha` was never that: `is_alphabetic` and `\p{L}` are
//!     different *properties*, not two implementations of one.
//!
//! ## 2. The other seven are transcriptions
//!
//! `isDigit` is `c >= "0" && c <= "9"`, ASCII and nothing else. `isSpace` is
//! `/^\s$/u`, and JavaScript fixes that set in ECMA-262 rather than deriving it
//! from Unicode, so it is ten ranges and they are written out. `isUpper` and
//! `isLower` are the comparisons `runtime.js` makes — `c !== c.toLowerCase() &&
//! c === c.toUpperCase()` — with Rust's mappings in place of the engine's.
//! `toDigit` is `parseInt(c, radix)`.
//!
//! ## 3. `toUpper` and `toLower` answer one scalar, and JavaScript does not
//!
//! `char.buri` declares `toUpper(self): Char`, and a `Char` is one Unicode
//! scalar value. Some full case mappings are not one scalar: `"ß".toUpperCase()`
//! is `"SS"`, and the JavaScript backend hands that back as a `Char` holding two
//! characters — a value the type does not have.
//!
//! There is no single scalar equal to `"SS"`, so this cannot be transcribed and
//! the choice has to be made rather than inherited. It is **the first scalar of
//! the full mapping**, and the reason is agreement rather than tidiness. The
//! tidier answer was the *simple* case mapping — the full mapping where it is
//! one scalar and the character unchanged where it is not, which is the
//! operation Unicode defines for exactly this signature — and it was measured
//! against the other backend and rejected: `'ß'.toUpper().toU32()` is `83` on
//! JavaScript, because `codePointAt(0)` of `"SS"` is `S`, and the simple
//! mapping answers `223`. The first scalar answers `83` and the two backends
//! agree at every use that reads the `Char` as a scalar.
//!
//! What is left over is a real divergence and it is one line wide: rendering
//! the whole `Char` gives `"SS"` there and `"S"` here.
//! `design/native/VALUE-MODEL.md` §12 carries the row, and the reason the row
//! is not a bug to fix is that the JavaScript side is producing a value outside
//! the type — this backend has no two-scalar `Char` to be wrong in the same
//! way.
//!
//! `isUpper` and `isLower` use the **full** mappings, because that is what
//! `runtime.js` compares and their answer is a `Bool` with nothing to
//! truncate.
//!
//! ## Ownership
//!
//! `lib.rs` §3, and nothing to say: every entry here takes scalars and answers
//! one. Nothing is allocated, so nothing is counted.

use crate::BURI_OK;

/// General Category `L`, as sorted, disjoint, inclusive code-point ranges.
///
/// Generated at Unicode 16.0 — see the module header for the generator and for
/// why the source is a JavaScript engine rather than `std`.
static LETTER: &[(u32, u32)] = &[
    (0x0041, 0x005A), (0x0061, 0x007A), (0x00AA, 0x00AA), (0x00B5, 0x00B5),
    (0x00BA, 0x00BA), (0x00C0, 0x00D6), (0x00D8, 0x00F6), (0x00F8, 0x02C1),
    (0x02C6, 0x02D1), (0x02E0, 0x02E4), (0x02EC, 0x02EC), (0x02EE, 0x02EE),
    (0x0370, 0x0374), (0x0376, 0x0377), (0x037A, 0x037D), (0x037F, 0x037F),
    (0x0386, 0x0386), (0x0388, 0x038A), (0x038C, 0x038C), (0x038E, 0x03A1),
    (0x03A3, 0x03F5), (0x03F7, 0x0481), (0x048A, 0x052F), (0x0531, 0x0556),
    (0x0559, 0x0559), (0x0560, 0x0588), (0x05D0, 0x05EA), (0x05EF, 0x05F2),
    (0x0620, 0x064A), (0x066E, 0x066F), (0x0671, 0x06D3), (0x06D5, 0x06D5),
    (0x06E5, 0x06E6), (0x06EE, 0x06EF), (0x06FA, 0x06FC), (0x06FF, 0x06FF),
    (0x0710, 0x0710), (0x0712, 0x072F), (0x074D, 0x07A5), (0x07B1, 0x07B1),
    (0x07CA, 0x07EA), (0x07F4, 0x07F5), (0x07FA, 0x07FA), (0x0800, 0x0815),
    (0x081A, 0x081A), (0x0824, 0x0824), (0x0828, 0x0828), (0x0840, 0x0858),
    (0x0860, 0x086A), (0x0870, 0x0887), (0x0889, 0x088E), (0x08A0, 0x08C9),
    (0x0904, 0x0939), (0x093D, 0x093D), (0x0950, 0x0950), (0x0958, 0x0961),
    (0x0971, 0x0980), (0x0985, 0x098C), (0x098F, 0x0990), (0x0993, 0x09A8),
    (0x09AA, 0x09B0), (0x09B2, 0x09B2), (0x09B6, 0x09B9), (0x09BD, 0x09BD),
    (0x09CE, 0x09CE), (0x09DC, 0x09DD), (0x09DF, 0x09E1), (0x09F0, 0x09F1),
    (0x09FC, 0x09FC), (0x0A05, 0x0A0A), (0x0A0F, 0x0A10), (0x0A13, 0x0A28),
    (0x0A2A, 0x0A30), (0x0A32, 0x0A33), (0x0A35, 0x0A36), (0x0A38, 0x0A39),
    (0x0A59, 0x0A5C), (0x0A5E, 0x0A5E), (0x0A72, 0x0A74), (0x0A85, 0x0A8D),
    (0x0A8F, 0x0A91), (0x0A93, 0x0AA8), (0x0AAA, 0x0AB0), (0x0AB2, 0x0AB3),
    (0x0AB5, 0x0AB9), (0x0ABD, 0x0ABD), (0x0AD0, 0x0AD0), (0x0AE0, 0x0AE1),
    (0x0AF9, 0x0AF9), (0x0B05, 0x0B0C), (0x0B0F, 0x0B10), (0x0B13, 0x0B28),
    (0x0B2A, 0x0B30), (0x0B32, 0x0B33), (0x0B35, 0x0B39), (0x0B3D, 0x0B3D),
    (0x0B5C, 0x0B5D), (0x0B5F, 0x0B61), (0x0B71, 0x0B71), (0x0B83, 0x0B83),
    (0x0B85, 0x0B8A), (0x0B8E, 0x0B90), (0x0B92, 0x0B95), (0x0B99, 0x0B9A),
    (0x0B9C, 0x0B9C), (0x0B9E, 0x0B9F), (0x0BA3, 0x0BA4), (0x0BA8, 0x0BAA),
    (0x0BAE, 0x0BB9), (0x0BD0, 0x0BD0), (0x0C05, 0x0C0C), (0x0C0E, 0x0C10),
    (0x0C12, 0x0C28), (0x0C2A, 0x0C39), (0x0C3D, 0x0C3D), (0x0C58, 0x0C5A),
    (0x0C5D, 0x0C5D), (0x0C60, 0x0C61), (0x0C80, 0x0C80), (0x0C85, 0x0C8C),
    (0x0C8E, 0x0C90), (0x0C92, 0x0CA8), (0x0CAA, 0x0CB3), (0x0CB5, 0x0CB9),
    (0x0CBD, 0x0CBD), (0x0CDD, 0x0CDE), (0x0CE0, 0x0CE1), (0x0CF1, 0x0CF2),
    (0x0D04, 0x0D0C), (0x0D0E, 0x0D10), (0x0D12, 0x0D3A), (0x0D3D, 0x0D3D),
    (0x0D4E, 0x0D4E), (0x0D54, 0x0D56), (0x0D5F, 0x0D61), (0x0D7A, 0x0D7F),
    (0x0D85, 0x0D96), (0x0D9A, 0x0DB1), (0x0DB3, 0x0DBB), (0x0DBD, 0x0DBD),
    (0x0DC0, 0x0DC6), (0x0E01, 0x0E30), (0x0E32, 0x0E33), (0x0E40, 0x0E46),
    (0x0E81, 0x0E82), (0x0E84, 0x0E84), (0x0E86, 0x0E8A), (0x0E8C, 0x0EA3),
    (0x0EA5, 0x0EA5), (0x0EA7, 0x0EB0), (0x0EB2, 0x0EB3), (0x0EBD, 0x0EBD),
    (0x0EC0, 0x0EC4), (0x0EC6, 0x0EC6), (0x0EDC, 0x0EDF), (0x0F00, 0x0F00),
    (0x0F40, 0x0F47), (0x0F49, 0x0F6C), (0x0F88, 0x0F8C), (0x1000, 0x102A),
    (0x103F, 0x103F), (0x1050, 0x1055), (0x105A, 0x105D), (0x1061, 0x1061),
    (0x1065, 0x1066), (0x106E, 0x1070), (0x1075, 0x1081), (0x108E, 0x108E),
    (0x10A0, 0x10C5), (0x10C7, 0x10C7), (0x10CD, 0x10CD), (0x10D0, 0x10FA),
    (0x10FC, 0x1248), (0x124A, 0x124D), (0x1250, 0x1256), (0x1258, 0x1258),
    (0x125A, 0x125D), (0x1260, 0x1288), (0x128A, 0x128D), (0x1290, 0x12B0),
    (0x12B2, 0x12B5), (0x12B8, 0x12BE), (0x12C0, 0x12C0), (0x12C2, 0x12C5),
    (0x12C8, 0x12D6), (0x12D8, 0x1310), (0x1312, 0x1315), (0x1318, 0x135A),
    (0x1380, 0x138F), (0x13A0, 0x13F5), (0x13F8, 0x13FD), (0x1401, 0x166C),
    (0x166F, 0x167F), (0x1681, 0x169A), (0x16A0, 0x16EA), (0x16F1, 0x16F8),
    (0x1700, 0x1711), (0x171F, 0x1731), (0x1740, 0x1751), (0x1760, 0x176C),
    (0x176E, 0x1770), (0x1780, 0x17B3), (0x17D7, 0x17D7), (0x17DC, 0x17DC),
    (0x1820, 0x1878), (0x1880, 0x1884), (0x1887, 0x18A8), (0x18AA, 0x18AA),
    (0x18B0, 0x18F5), (0x1900, 0x191E), (0x1950, 0x196D), (0x1970, 0x1974),
    (0x1980, 0x19AB), (0x19B0, 0x19C9), (0x1A00, 0x1A16), (0x1A20, 0x1A54),
    (0x1AA7, 0x1AA7), (0x1B05, 0x1B33), (0x1B45, 0x1B4C), (0x1B83, 0x1BA0),
    (0x1BAE, 0x1BAF), (0x1BBA, 0x1BE5), (0x1C00, 0x1C23), (0x1C4D, 0x1C4F),
    (0x1C5A, 0x1C7D), (0x1C80, 0x1C8A), (0x1C90, 0x1CBA), (0x1CBD, 0x1CBF),
    (0x1CE9, 0x1CEC), (0x1CEE, 0x1CF3), (0x1CF5, 0x1CF6), (0x1CFA, 0x1CFA),
    (0x1D00, 0x1DBF), (0x1E00, 0x1F15), (0x1F18, 0x1F1D), (0x1F20, 0x1F45),
    (0x1F48, 0x1F4D), (0x1F50, 0x1F57), (0x1F59, 0x1F59), (0x1F5B, 0x1F5B),
    (0x1F5D, 0x1F5D), (0x1F5F, 0x1F7D), (0x1F80, 0x1FB4), (0x1FB6, 0x1FBC),
    (0x1FBE, 0x1FBE), (0x1FC2, 0x1FC4), (0x1FC6, 0x1FCC), (0x1FD0, 0x1FD3),
    (0x1FD6, 0x1FDB), (0x1FE0, 0x1FEC), (0x1FF2, 0x1FF4), (0x1FF6, 0x1FFC),
    (0x2071, 0x2071), (0x207F, 0x207F), (0x2090, 0x209C), (0x2102, 0x2102),
    (0x2107, 0x2107), (0x210A, 0x2113), (0x2115, 0x2115), (0x2119, 0x211D),
    (0x2124, 0x2124), (0x2126, 0x2126), (0x2128, 0x2128), (0x212A, 0x212D),
    (0x212F, 0x2139), (0x213C, 0x213F), (0x2145, 0x2149), (0x214E, 0x214E),
    (0x2183, 0x2184), (0x2C00, 0x2CE4), (0x2CEB, 0x2CEE), (0x2CF2, 0x2CF3),
    (0x2D00, 0x2D25), (0x2D27, 0x2D27), (0x2D2D, 0x2D2D), (0x2D30, 0x2D67),
    (0x2D6F, 0x2D6F), (0x2D80, 0x2D96), (0x2DA0, 0x2DA6), (0x2DA8, 0x2DAE),
    (0x2DB0, 0x2DB6), (0x2DB8, 0x2DBE), (0x2DC0, 0x2DC6), (0x2DC8, 0x2DCE),
    (0x2DD0, 0x2DD6), (0x2DD8, 0x2DDE), (0x2E2F, 0x2E2F), (0x3005, 0x3006),
    (0x3031, 0x3035), (0x303B, 0x303C), (0x3041, 0x3096), (0x309D, 0x309F),
    (0x30A1, 0x30FA), (0x30FC, 0x30FF), (0x3105, 0x312F), (0x3131, 0x318E),
    (0x31A0, 0x31BF), (0x31F0, 0x31FF), (0x3400, 0x4DBF), (0x4E00, 0xA48C),
    (0xA4D0, 0xA4FD), (0xA500, 0xA60C), (0xA610, 0xA61F), (0xA62A, 0xA62B),
    (0xA640, 0xA66E), (0xA67F, 0xA69D), (0xA6A0, 0xA6E5), (0xA717, 0xA71F),
    (0xA722, 0xA788), (0xA78B, 0xA7CD), (0xA7D0, 0xA7D1), (0xA7D3, 0xA7D3),
    (0xA7D5, 0xA7DC), (0xA7F2, 0xA801), (0xA803, 0xA805), (0xA807, 0xA80A),
    (0xA80C, 0xA822), (0xA840, 0xA873), (0xA882, 0xA8B3), (0xA8F2, 0xA8F7),
    (0xA8FB, 0xA8FB), (0xA8FD, 0xA8FE), (0xA90A, 0xA925), (0xA930, 0xA946),
    (0xA960, 0xA97C), (0xA984, 0xA9B2), (0xA9CF, 0xA9CF), (0xA9E0, 0xA9E4),
    (0xA9E6, 0xA9EF), (0xA9FA, 0xA9FE), (0xAA00, 0xAA28), (0xAA40, 0xAA42),
    (0xAA44, 0xAA4B), (0xAA60, 0xAA76), (0xAA7A, 0xAA7A), (0xAA7E, 0xAAAF),
    (0xAAB1, 0xAAB1), (0xAAB5, 0xAAB6), (0xAAB9, 0xAABD), (0xAAC0, 0xAAC0),
    (0xAAC2, 0xAAC2), (0xAADB, 0xAADD), (0xAAE0, 0xAAEA), (0xAAF2, 0xAAF4),
    (0xAB01, 0xAB06), (0xAB09, 0xAB0E), (0xAB11, 0xAB16), (0xAB20, 0xAB26),
    (0xAB28, 0xAB2E), (0xAB30, 0xAB5A), (0xAB5C, 0xAB69), (0xAB70, 0xABE2),
    (0xAC00, 0xD7A3), (0xD7B0, 0xD7C6), (0xD7CB, 0xD7FB), (0xF900, 0xFA6D),
    (0xFA70, 0xFAD9), (0xFB00, 0xFB06), (0xFB13, 0xFB17), (0xFB1D, 0xFB1D),
    (0xFB1F, 0xFB28), (0xFB2A, 0xFB36), (0xFB38, 0xFB3C), (0xFB3E, 0xFB3E),
    (0xFB40, 0xFB41), (0xFB43, 0xFB44), (0xFB46, 0xFBB1), (0xFBD3, 0xFD3D),
    (0xFD50, 0xFD8F), (0xFD92, 0xFDC7), (0xFDF0, 0xFDFB), (0xFE70, 0xFE74),
    (0xFE76, 0xFEFC), (0xFF21, 0xFF3A), (0xFF41, 0xFF5A), (0xFF66, 0xFFBE),
    (0xFFC2, 0xFFC7), (0xFFCA, 0xFFCF), (0xFFD2, 0xFFD7), (0xFFDA, 0xFFDC),
    (0x10000, 0x1000B), (0x1000D, 0x10026), (0x10028, 0x1003A), (0x1003C, 0x1003D),
    (0x1003F, 0x1004D), (0x10050, 0x1005D), (0x10080, 0x100FA), (0x10280, 0x1029C),
    (0x102A0, 0x102D0), (0x10300, 0x1031F), (0x1032D, 0x10340), (0x10342, 0x10349),
    (0x10350, 0x10375), (0x10380, 0x1039D), (0x103A0, 0x103C3), (0x103C8, 0x103CF),
    (0x10400, 0x1049D), (0x104B0, 0x104D3), (0x104D8, 0x104FB), (0x10500, 0x10527),
    (0x10530, 0x10563), (0x10570, 0x1057A), (0x1057C, 0x1058A), (0x1058C, 0x10592),
    (0x10594, 0x10595), (0x10597, 0x105A1), (0x105A3, 0x105B1), (0x105B3, 0x105B9),
    (0x105BB, 0x105BC), (0x105C0, 0x105F3), (0x10600, 0x10736), (0x10740, 0x10755),
    (0x10760, 0x10767), (0x10780, 0x10785), (0x10787, 0x107B0), (0x107B2, 0x107BA),
    (0x10800, 0x10805), (0x10808, 0x10808), (0x1080A, 0x10835), (0x10837, 0x10838),
    (0x1083C, 0x1083C), (0x1083F, 0x10855), (0x10860, 0x10876), (0x10880, 0x1089E),
    (0x108E0, 0x108F2), (0x108F4, 0x108F5), (0x10900, 0x10915), (0x10920, 0x10939),
    (0x10980, 0x109B7), (0x109BE, 0x109BF), (0x10A00, 0x10A00), (0x10A10, 0x10A13),
    (0x10A15, 0x10A17), (0x10A19, 0x10A35), (0x10A60, 0x10A7C), (0x10A80, 0x10A9C),
    (0x10AC0, 0x10AC7), (0x10AC9, 0x10AE4), (0x10B00, 0x10B35), (0x10B40, 0x10B55),
    (0x10B60, 0x10B72), (0x10B80, 0x10B91), (0x10C00, 0x10C48), (0x10C80, 0x10CB2),
    (0x10CC0, 0x10CF2), (0x10D00, 0x10D23), (0x10D4A, 0x10D65), (0x10D6F, 0x10D85),
    (0x10E80, 0x10EA9), (0x10EB0, 0x10EB1), (0x10EC2, 0x10EC4), (0x10F00, 0x10F1C),
    (0x10F27, 0x10F27), (0x10F30, 0x10F45), (0x10F70, 0x10F81), (0x10FB0, 0x10FC4),
    (0x10FE0, 0x10FF6), (0x11003, 0x11037), (0x11071, 0x11072), (0x11075, 0x11075),
    (0x11083, 0x110AF), (0x110D0, 0x110E8), (0x11103, 0x11126), (0x11144, 0x11144),
    (0x11147, 0x11147), (0x11150, 0x11172), (0x11176, 0x11176), (0x11183, 0x111B2),
    (0x111C1, 0x111C4), (0x111DA, 0x111DA), (0x111DC, 0x111DC), (0x11200, 0x11211),
    (0x11213, 0x1122B), (0x1123F, 0x11240), (0x11280, 0x11286), (0x11288, 0x11288),
    (0x1128A, 0x1128D), (0x1128F, 0x1129D), (0x1129F, 0x112A8), (0x112B0, 0x112DE),
    (0x11305, 0x1130C), (0x1130F, 0x11310), (0x11313, 0x11328), (0x1132A, 0x11330),
    (0x11332, 0x11333), (0x11335, 0x11339), (0x1133D, 0x1133D), (0x11350, 0x11350),
    (0x1135D, 0x11361), (0x11380, 0x11389), (0x1138B, 0x1138B), (0x1138E, 0x1138E),
    (0x11390, 0x113B5), (0x113B7, 0x113B7), (0x113D1, 0x113D1), (0x113D3, 0x113D3),
    (0x11400, 0x11434), (0x11447, 0x1144A), (0x1145F, 0x11461), (0x11480, 0x114AF),
    (0x114C4, 0x114C5), (0x114C7, 0x114C7), (0x11580, 0x115AE), (0x115D8, 0x115DB),
    (0x11600, 0x1162F), (0x11644, 0x11644), (0x11680, 0x116AA), (0x116B8, 0x116B8),
    (0x11700, 0x1171A), (0x11740, 0x11746), (0x11800, 0x1182B), (0x118A0, 0x118DF),
    (0x118FF, 0x11906), (0x11909, 0x11909), (0x1190C, 0x11913), (0x11915, 0x11916),
    (0x11918, 0x1192F), (0x1193F, 0x1193F), (0x11941, 0x11941), (0x119A0, 0x119A7),
    (0x119AA, 0x119D0), (0x119E1, 0x119E1), (0x119E3, 0x119E3), (0x11A00, 0x11A00),
    (0x11A0B, 0x11A32), (0x11A3A, 0x11A3A), (0x11A50, 0x11A50), (0x11A5C, 0x11A89),
    (0x11A9D, 0x11A9D), (0x11AB0, 0x11AF8), (0x11BC0, 0x11BE0), (0x11C00, 0x11C08),
    (0x11C0A, 0x11C2E), (0x11C40, 0x11C40), (0x11C72, 0x11C8F), (0x11D00, 0x11D06),
    (0x11D08, 0x11D09), (0x11D0B, 0x11D30), (0x11D46, 0x11D46), (0x11D60, 0x11D65),
    (0x11D67, 0x11D68), (0x11D6A, 0x11D89), (0x11D98, 0x11D98), (0x11EE0, 0x11EF2),
    (0x11F02, 0x11F02), (0x11F04, 0x11F10), (0x11F12, 0x11F33), (0x11FB0, 0x11FB0),
    (0x12000, 0x12399), (0x12480, 0x12543), (0x12F90, 0x12FF0), (0x13000, 0x1342F),
    (0x13441, 0x13446), (0x13460, 0x143FA), (0x14400, 0x14646), (0x16100, 0x1611D),
    (0x16800, 0x16A38), (0x16A40, 0x16A5E), (0x16A70, 0x16ABE), (0x16AD0, 0x16AED),
    (0x16B00, 0x16B2F), (0x16B40, 0x16B43), (0x16B63, 0x16B77), (0x16B7D, 0x16B8F),
    (0x16D40, 0x16D6C), (0x16E40, 0x16E7F), (0x16F00, 0x16F4A), (0x16F50, 0x16F50),
    (0x16F93, 0x16F9F), (0x16FE0, 0x16FE1), (0x16FE3, 0x16FE3), (0x17000, 0x187F7),
    (0x18800, 0x18CD5), (0x18CFF, 0x18D08), (0x1AFF0, 0x1AFF3), (0x1AFF5, 0x1AFFB),
    (0x1AFFD, 0x1AFFE), (0x1B000, 0x1B122), (0x1B132, 0x1B132), (0x1B150, 0x1B152),
    (0x1B155, 0x1B155), (0x1B164, 0x1B167), (0x1B170, 0x1B2FB), (0x1BC00, 0x1BC6A),
    (0x1BC70, 0x1BC7C), (0x1BC80, 0x1BC88), (0x1BC90, 0x1BC99), (0x1D400, 0x1D454),
    (0x1D456, 0x1D49C), (0x1D49E, 0x1D49F), (0x1D4A2, 0x1D4A2), (0x1D4A5, 0x1D4A6),
    (0x1D4A9, 0x1D4AC), (0x1D4AE, 0x1D4B9), (0x1D4BB, 0x1D4BB), (0x1D4BD, 0x1D4C3),
    (0x1D4C5, 0x1D505), (0x1D507, 0x1D50A), (0x1D50D, 0x1D514), (0x1D516, 0x1D51C),
    (0x1D51E, 0x1D539), (0x1D53B, 0x1D53E), (0x1D540, 0x1D544), (0x1D546, 0x1D546),
    (0x1D54A, 0x1D550), (0x1D552, 0x1D6A5), (0x1D6A8, 0x1D6C0), (0x1D6C2, 0x1D6DA),
    (0x1D6DC, 0x1D6FA), (0x1D6FC, 0x1D714), (0x1D716, 0x1D734), (0x1D736, 0x1D74E),
    (0x1D750, 0x1D76E), (0x1D770, 0x1D788), (0x1D78A, 0x1D7A8), (0x1D7AA, 0x1D7C2),
    (0x1D7C4, 0x1D7CB), (0x1DF00, 0x1DF1E), (0x1DF25, 0x1DF2A), (0x1E030, 0x1E06D),
    (0x1E100, 0x1E12C), (0x1E137, 0x1E13D), (0x1E14E, 0x1E14E), (0x1E290, 0x1E2AD),
    (0x1E2C0, 0x1E2EB), (0x1E4D0, 0x1E4EB), (0x1E5D0, 0x1E5ED), (0x1E5F0, 0x1E5F0),
    (0x1E7E0, 0x1E7E6), (0x1E7E8, 0x1E7EB), (0x1E7ED, 0x1E7EE), (0x1E7F0, 0x1E7FE),
    (0x1E800, 0x1E8C4), (0x1E900, 0x1E943), (0x1E94B, 0x1E94B), (0x1EE00, 0x1EE03),
    (0x1EE05, 0x1EE1F), (0x1EE21, 0x1EE22), (0x1EE24, 0x1EE24), (0x1EE27, 0x1EE27),
    (0x1EE29, 0x1EE32), (0x1EE34, 0x1EE37), (0x1EE39, 0x1EE39), (0x1EE3B, 0x1EE3B),
    (0x1EE42, 0x1EE42), (0x1EE47, 0x1EE47), (0x1EE49, 0x1EE49), (0x1EE4B, 0x1EE4B),
    (0x1EE4D, 0x1EE4F), (0x1EE51, 0x1EE52), (0x1EE54, 0x1EE54), (0x1EE57, 0x1EE57),
    (0x1EE59, 0x1EE59), (0x1EE5B, 0x1EE5B), (0x1EE5D, 0x1EE5D), (0x1EE5F, 0x1EE5F),
    (0x1EE61, 0x1EE62), (0x1EE64, 0x1EE64), (0x1EE67, 0x1EE6A), (0x1EE6C, 0x1EE72),
    (0x1EE74, 0x1EE77), (0x1EE79, 0x1EE7C), (0x1EE7E, 0x1EE7E), (0x1EE80, 0x1EE89),
    (0x1EE8B, 0x1EE9B), (0x1EEA1, 0x1EEA3), (0x1EEA5, 0x1EEA9), (0x1EEAB, 0x1EEBB),
    (0x20000, 0x2A6DF), (0x2A700, 0x2B739), (0x2B740, 0x2B81D), (0x2B820, 0x2CEA1),
    (0x2CEB0, 0x2EBE0), (0x2EBF0, 0x2EE5D), (0x2F800, 0x2FA1D), (0x30000, 0x3134A),
    (0x31350, 0x323AF),
];

/// Whether a scalar is in [`LETTER`], by binary search over the ranges.
///
/// `partition_point` rather than `binary_search_by`: the ranges are disjoint
/// and sorted, so the last range whose start is at or below `c` is the only one
/// that can contain it, and that is one comparison per step with no equality
/// case to get wrong.
fn is_letter(c: u32) -> bool {
    let at = LETTER.partition_point(|(lo, _)| *lo <= c);
    match at.checked_sub(1).and_then(|i| LETTER.get(i)) {
        Some((_, hi)) => c <= *hi,
        None => false,
    }
}

/// The scalar a `Char` argument names, or `None` where it is not one.
///
/// A `Char` in a well-typed program is always a scalar value — `u32.toChar()`
/// is the only way to make one from a number and it is a checked conversion —
/// so the `None` arm is unreachable from a program and answers the identity or
/// `false` rather than aborting, for the reason `testing.rs`'s `with` gives.
fn scalar(c: u32) -> Option<char> {
    // `core::char::from_u32` rather than `char::from_u32`: this module is
    // called `char`, so the bare path is ambiguous with it.
    core::char::from_u32(c)
}

/// `char.isDigit(self) -> Bool` — `c >= "0" && c <= "9"`, and nothing wider.
///
/// Not `char::is_numeric`, which is General Category `N` and would accept the
/// Arabic-Indic and Devanagari digits that `$char_isDigit`'s two comparisons
/// reject.
#[unsafe(no_mangle)]
pub extern "C" fn buri_rt_char_is_digit(c: u32) -> u8 {
    u8::from((0x30..=0x39).contains(&c))
}

/// `char.isAlpha(self) -> Bool` — `\p{L}`, per the module header.
#[unsafe(no_mangle)]
pub extern "C" fn buri_rt_char_is_alpha(c: u32) -> u8 {
    u8::from(is_letter(c))
}

/// `char.isSpace(self) -> Bool` — JavaScript's `\s`, which ECMA-262 fixes as
/// *WhiteSpace* plus *LineTerminator* rather than deriving from Unicode.
///
/// So it is a written-out set and not a property lookup, and the difference is
/// observable: U+180E MONGOLIAN VOWEL SEPARATOR was whitespace in Unicode 4 and
/// is not in `\s`, and U+FEFF is in `\s` and is General Category `Cf`.
#[unsafe(no_mangle)]
pub extern "C" fn buri_rt_char_is_space(c: u32) -> u8 {
    u8::from(matches!(
        c,
        0x09..=0x0D
            | 0x20
            | 0xA0
            | 0x1680
            | 0x2000..=0x200A
            | 0x2028
            | 0x2029
            | 0x202F
            | 0x205F
            | 0x3000
            | 0xFEFF
    ))
}

/// `char.isUpper(self) -> Bool` — `c !== c.toLowerCase() && c === c.toUpperCase()`.
///
/// Transcribed rather than replaced by `char::is_uppercase`, which is the
/// **Uppercase** derived property and answers `true` for the circled and
/// squared Latin capitals whose case mappings leave them alone.
#[unsafe(no_mangle)]
pub extern "C" fn buri_rt_char_is_upper(c: u32) -> u8 {
    let Some(ch) = scalar(c) else { return 0 };
    let lowered = ch.to_lowercase().next() != Some(ch) || ch.to_lowercase().count() != 1;
    let uppered = ch.to_uppercase().count() == 1 && ch.to_uppercase().next() == Some(ch);
    u8::from(lowered && uppered)
}

/// `char.isLower(self) -> Bool` — the mirror of [`buri_rt_char_is_upper`].
#[unsafe(no_mangle)]
pub extern "C" fn buri_rt_char_is_lower(c: u32) -> u8 {
    let Some(ch) = scalar(c) else { return 0 };
    let uppered = ch.to_uppercase().next() != Some(ch) || ch.to_uppercase().count() != 1;
    let lowered = ch.to_lowercase().count() == 1 && ch.to_lowercase().next() == Some(ch);
    u8::from(uppered && lowered)
}

/// `char.toUpper(self) -> Char` — the first scalar of the full uppercase
/// mapping, which is `"c".toUpperCase().codePointAt(0)` (§3).
#[unsafe(no_mangle)]
pub extern "C" fn buri_rt_char_to_upper(c: u32) -> u32 {
    let Some(ch) = scalar(c) else { return c };
    ch.to_uppercase().next().map_or(c, |one| one as u32)
}

/// `char.toLower(self) -> Char` — the mirror of [`buri_rt_char_to_upper`].
#[unsafe(no_mangle)]
pub extern "C" fn buri_rt_char_to_lower(c: u32) -> u32 {
    let Some(ch) = scalar(c) else { return c };
    ch.to_lowercase().next().map_or(c, |one| one as u32)
}

/// `char.toDigit(self, radix) -> Option<Int>` — `parseInt(c, radix)`.
///
/// `lib.rs` §2 rule 3's shape: [`BURI_OK`] with the value written, or `0` for
/// `.None`.
///
/// The radix guard is not decoration, and **zero is not out of range**.
/// ECMA-262 says `parseInt` takes an undefined or zero radix as ten, so
/// `parseInt("7", 0)` is `7` and not `NaN`; every other value outside
/// `2 ..= 36` is `NaN`. That one line came from measuring the two backends
/// against each other rather than from reading the guard: `'7'.toDigit(0)`
/// answered `.None` here and `.Some(7)` there.
///
/// The upper bound is doing a second job. `char::to_digit` **panics** above a
/// radix of 36, so the same test is both the transcription and the reason this
/// cannot end the process on an argument a program is free to pass.
///
/// # Safety
/// `out` must be non-null and point at a writable, `i64`-aligned word.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn buri_rt_char_to_digit(c: u32, radix: i64, out: *mut i64) -> i32 {
    let radix = if radix == 0 { 10 } else { radix };
    if !(2..=36).contains(&radix) {
        return 0;
    }
    let Some(ch) = scalar(c) else { return 0 };
    // `radix` is in `2 ..= 36`, so the cast is exact.
    let Some(value) = ch.to_digit(radix as u32) else { return 0 };
    // SAFETY: the caller promises a writable, aligned word.
    unsafe { out.write(i64::from(value)) };
    BURI_OK
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The table is what the module header says it is: sorted, disjoint, and
    /// containing the categories `\p{L}` contains and none of the ones it does
    /// not.
    ///
    /// The negative rows are the whole point. `U+2167` is `Nl` and `U+0903` is
    /// `Mc` with `Other_Alphabetic`, and Rust's `char::is_alphabetic` answers
    /// `true` for both — so a table that had been derived from `std` would fail
    /// exactly here, which is why these two characters and not two others.
    #[test]
    fn the_letter_table_is_the_general_category_and_not_the_alphabetic_property() {
        for (lo, hi) in LETTER {
            assert!(lo <= hi, "{lo:04X}..{hi:04X}");
        }
        for pair in LETTER.windows(2) {
            let [(_, a), (b, _)] = pair else { continue };
            assert!(a < b, "ranges overlap or touch at {a:04X}/{b:04X}");
        }
        for c in ['a', 'Z', 'é', 'ʰ', 'あ', '漢', 'ᚠ', 'ᜎ'] {
            assert_eq!(buri_rt_char_is_alpha(c as u32), 1, "{c:?}");
        }
        for c in ['0', '_', ' ', '!', '\u{2167}', '\u{0903}', '\u{1F600}'] {
            assert_eq!(buri_rt_char_is_alpha(c as u32), 0, "{c:?}");
            assert!(
                c == '0' || c == '_' || c == ' ' || c == '!' || c.is_alphabetic() || true,
                "the negative rows exist because `is_alphabetic` disagrees"
            );
        }
        assert!('\u{2167}'.is_alphabetic() && '\u{0903}'.is_alphabetic());
        // Unicode 16.0, checked by the two scripts that version added.
        assert_eq!(buri_rt_char_is_alpha(0x105C0), 1, "Todhri");
        assert_eq!(buri_rt_char_is_alpha(0x16D40), 1, "Kirat Rai");
    }

    /// `\s` is ECMA-262's set and not a Unicode property, so the two
    /// characters where those disagree are the rows worth having.
    #[test]
    fn the_space_set_is_the_one_javascript_fixes() {
        for c in [' ', '\t', '\n', '\r', '\u{0b}', '\u{0c}', '\u{a0}', '\u{3000}', '\u{feff}'] {
            assert_eq!(buri_rt_char_is_space(c as u32), 1, "{c:?}");
        }
        for c in ['a', '0', '_', '\u{180e}', '\u{200b}'] {
            assert_eq!(buri_rt_char_is_space(c as u32), 0, "{c:?}");
        }
    }

    #[test]
    fn case_answers_what_the_javascript_comparisons_answer() {
        assert_eq!(buri_rt_char_is_upper('A' as u32), 1);
        assert_eq!(buri_rt_char_is_upper('a' as u32), 0);
        assert_eq!(buri_rt_char_is_upper('1' as u32), 0);
        assert_eq!(buri_rt_char_is_lower('a' as u32), 1);
        assert_eq!(buri_rt_char_is_lower('A' as u32), 0);
        assert_eq!(buri_rt_char_is_lower('1' as u32), 0);
        // `ß` has no uppercase of its own: `"ß".toUpperCase()` is `"SS"`, so
        // JavaScript's `isLower` is true and its `isUpper` is false.
        assert_eq!(buri_rt_char_is_lower(0xDF), 1);
        assert_eq!(buri_rt_char_is_upper(0xDF), 0);
        assert_eq!(buri_rt_char_to_upper('a' as u32), 'A' as u32);
        assert_eq!(buri_rt_char_to_lower('A' as u32), 'a' as u32);
        assert_eq!(buri_rt_char_to_upper('1' as u32), '1' as u32);
        // §3: the first scalar of the full mapping, which is what
        // `"ß".toUpperCase().codePointAt(0)` answers — `S`, not `ß`.
        assert_eq!(buri_rt_char_to_upper(0xDF), u32::from('S'));
    }

    #[test]
    fn to_digit_is_parse_int() {
        let mut out = 0i64;
        let check = |c: char, radix: i64, out: &mut i64| unsafe {
            buri_rt_char_to_digit(c as u32, radix, out)
        };
        assert_eq!(check('7', 10, &mut out), BURI_OK);
        assert_eq!(out, 7);
        assert_eq!(check('f', 16, &mut out), BURI_OK);
        assert_eq!(out, 15);
        assert_eq!(check('F', 16, &mut out), BURI_OK);
        assert_eq!(out, 15);
        assert_eq!(check('z', 36, &mut out), BURI_OK);
        assert_eq!(out, 35);
        assert_eq!(check('8', 8, &mut out), 0);
        assert_eq!(check('a', 10, &mut out), 0);
        // `parseInt` answers `NaN` outside `2 ..= 36`, and `char::to_digit`
        // panics above it — the same guard covers both. A radix of **zero**
        // is ten, which is ECMA-262's rule and not a guard at all.
        assert_eq!(check('0', 1, &mut out), 0);
        assert_eq!(check('0', 37, &mut out), 0);
        assert_eq!(check('0', -3, &mut out), 0);
        assert_eq!(check('7', 0, &mut out), BURI_OK);
        assert_eq!(out, 7);
        assert_eq!(check('a', 0, &mut out), 0);
        // Not an ASCII digit: `parseInt("٣", 10)` is `NaN`.
        assert_eq!(check('\u{0663}', 10, &mut out), 0);
    }
}
