//! **Ground truth from outside this repository**, replayed from checked-in
//! vectors.
//!
//! Both modules follow the same arrangement, and it is the arrangement that
//! makes them one binary rather than their subject: a tool this suite must not
//! depend on — a Lean toolchain, a C++ conformance runner — generates a file of
//! `(input, verdict)` pairs, the file is checked in, and `cargo test` replays
//! it needing nothing but a Buri toolchain. A suite that depends on a build of
//! another project is a suite that does not run.
//!
//! | Module | Vectors | Generated by |
//! |---|---|---|
//! | [`lean`] | `formal/vectors/exhaustiveness.txt` | `cd formal && lake env lean --run Vectors.lean` |
//! | [`proto`] | `proto/vectors.txt` | `cli/tests/proto/run.sh --record`, which drives protobuf's own `conformance_test_runner` |
//!
//! ```text
//! cargo test -p buri --test vectors
//! BURI_KEEP=1 cargo test -p buri --test vectors proto::   # keep the scratch tree
//! ```

#[path = "../harness/mod.rs"]
mod harness;

mod lean;
mod proto;
