//! **Ground truth from outside this repository**, replayed from checked-in
//! vectors.
//!
//! Both modules follow the same arrangement, and it is the arrangement that
//! makes them one binary rather than their subject: a tool this suite must not
//! depend on — a Lean toolchain, a C++ conformance runner — generates a file of
//! `(input, verdict)` pairs, the file is checked in, and `cargo test` replays
//! it needing nothing but a Buri toolchain. A suite that depends on a build of
//! another project is a suite that does not run.
//!
//! | Module | Vectors | Generated by |
//! |---|---|---|
//! | [`lean`] | `formal/vectors/exhaustiveness.txt` | `cd formal && lake env lean --run Vectors.lean` |
//! | [`proto`] | `proto/vectors.txt` | `cli/tests/proto/run.sh --record`, which drives protobuf's own `conformance_test_runner` |
//!
//! ```text
//! cargo test -p buri --test vectors
//! BURI_KEEP=1 cargo test -p buri --test vectors proto::   # keep the scratch tree
//! ```

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::string_slice,
    clippy::arithmetic_side_effects,
    clippy::print_stdout,
    clippy::print_stderr,
    reason = "test code. The lint set in `Cargo.toml` pins a promise about the \
              toolchain — that no input panics it — and a harness that drives \
              the toolchain is not the toolchain. A test that unwraps fails on \
              the line that broke, which is what a test is for, and threading \
              `?` through an assertion buys nothing. `clippy.toml` exempts \
              `#[test]` functions already; this covers the helpers around them."
)]

#[path = "../harness/mod.rs"]
mod harness;

mod lean;
mod proto;
